project:
  type: website
  output-dir: docs
  preview:
    port: 4200
    browser: true
  render: 
    - "publicacoes"
    - "pessoas"
    - "index.qmd"
    - "grupos.qmd"
    - "areas-de-pesquisa.qmd"
    - "noticias"
    - "grupos"

website:
  title: "INTERAS"
  page-navigation: true
  favicon: images/favicon.ico
  navbar:
    toggle-position: right
#    background: light
    logo: images/logo_pt_transparente.png
    logo-alt: "INCT INTERAS"
    collapse-below: lg
    right:
      - text: "INCT INTERAS"
        menu: 
        - text: "O INCT INTERAS"
          href: sobre-o-interas.qmd
        - pessoas/coord-equipe.qmd
        - text: "ÁREAS DE PESQUISA"
          href: areas-de-pesquisa.qmd
        - text: "GRUPOS E LABORATÓRIOS"
          href: grupos.qmd
#        - text: O INCT EM NÚMEROS
#          href: interas-em-numeros.qmd
        - text: CONTATO
          href: contato.qmd
      - text: "PRODUÇÃO"
        menu:
        - text: "ARTIGOS"
          href: publicacoes/index.qmd
#        - text: "PREPRINTS"
#          href: preprints.qmd
      - noticias/index.qmd
#      - mulheresinteras/index.qmd
  page-footer: 
    left: 
     - text: |
          <img src="/images/3125_bordas_minimas_redim.png" alt="INTERAS" height="40">
    center: "Copyright 2025 INTERAS"
    right: 
      - icon: github
        href: https://github.com/ipencnensp/interaswebsite
      - icon: twitter 
        href: https://twitter.com/ 
  google-analytics: 'G-GSTPFS7CEE'
         
# Adicione esta seção para que o Quarto copie os diretórios de fotos
resources:
  - "pessoas/*/fotos/"
  - "images/*"
  - "images/grupos/*"
  
format:
  html:
    theme: 
      - materia
      - custom.scss
    css-vars:
      hero-bg: "url('images/topo_desvanecendo_sem_texto.jpeg')"

lang: pt-BR

execute: 
  freeze: auto
  
